services:
  nats:
    image: nats:latest
    container_name: notification-scheduler-nats
    hostname: nats
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
    restart:
        always
    volumes:
      - .image_resources/nats:/data
    healthcheck:
      test: echo 'PING' | nats --server localhost:4222 --timeout 5s
      interval: 3s
      timeout: 5s
      retries: 5