struct_field_align_threshold = 20
reorder_imports = true
imports_granularity = "Crate"
wrap_comments = true
max_width = 100
hard_tabs = true
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
struct_lit_single_line = true
struct_variant_width = 100
format_strings = true