[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
axum-prometheus = "0.8.0"
axum = { version = "0.8.3", features = ["macros"] }
tokio = { version = "1.37.0", features = ["full"]}
prometheus = { version = "0.14.0" }

