[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]

# env
dotenvy = "0.15.7"

# server
axum = "0.8.1"
axum-extra = {version = "0.10.0", features = ["cookie"]}
tokio = { version = "1.37.0", features = ["full"]}

# serde
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

# mongodb
mongodb = "3.2.3"

# utils
chrono = "0.4.38"
regex = "1.10.5"

[dev-dependencies]
anyhow = "1.0.82"
httpc-test = "0.1.9"