services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - .image_resources/mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 5s
      retries: 5
    container_name: notification-scheduler-api-mongodb
    hostname: mongodb

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - PORT=8000
      - APP_PORT=8000
      - PROMETHEUS_PORT=9090
      - MONGO_URI=mongodb://mongodb:27017/notification-scheduler
      - NATS_URL=nats:4222
    command: ["./api"]
    ports:
      - '8000:8000'
      - '9090:9090'
    depends_on:
      - mongodb