services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      timeout: 5s
      retries: 5
    container_name: notification-scheduler-api-mongodb
    hostname: mongodb